/** Declaration file generated by dts-gen */

/**
 * 经纬度对象
 */
interface Coordinate {
	/**
	 * 纬度
	 */
	lat: number;
	/**
	 * 经度
	 */
	lng: number;
}

/**
 * 经纬度转换配置参数
 */
interface CoordinateParam {
	/**
	 * 纬度
	 */
	lat: number;
	/**
	 * 经度
	 */
	lng: number;
	/**
	 * 来源格式 bmap-百度 tmap-腾讯 gmap-高德
	 */
	from: 'bmap' | 'tmap' | 'gmap';
	/**
	 * 目标格式 bmap-百度 tmap-腾讯 gmap-高德
	 */
	to: 'bmap' | 'tmap' | 'gmap';
}

/**
 * 经纬度转换 百度-->腾讯/高德
 * @param lng 经度
 * @param lat 纬度
 */
export function transBMapToTMap(lng: number, lat: number): Coordinate;

/**
 * 经纬度转换 腾讯/高德-->百度
 * @param lng 经度
 * @param lat 纬度
 */
export function transTMapToBMap(lng: number, lat: number): Coordinate;

/**
 * 经纬度转换 支持百度/腾讯/高德互转
 * @param params 配置参数
 * @example
 * ```
 * transCoordinate({
 * 	from: 'bmap',
 * 	to: 'gmap',
 * 	lat: 28.3131,
 * 	lng: 120.4242
 * })
 * ```
 * @return 返回示例： { lat: 28.2112, lng: 120.4242 }
 */
export function transCoordinate(params: CoordinateParam): Coordinate;
